const $=id=>document.getElementById(id);const screens=[...document.querySelectorAll('.screen')];let current=0,timers=[],urls=[];const themes={'Partner Spotlight':['#fff7f3','#d65c66'],'Adopt Me':['#fff5f5','#be1e2d'],'Fundraising':['#fff8e8','#c59635'],'Event':['#f8efff','#7b4b8f'],'Volunteer / Foster':['#eff8ff','#477a9c'],'Thank You':['#f4fff3','#5e8b58'],'Custom':['#fff7f3','#be1e2d']};
function show(n){current=n;screens.forEach((s,i)=>s.classList.toggle('active',i===n));$('status').textContent=`Screen ${n+1}`;}
function setTheme(){screens.forEach(s=>{s.style.setProperty('--c1',$('color1').value);s.style.setProperty('--c2',$('color2').value)})}
function fillWording(text){const cat=$('catName').value.trim()||'Our featured cat';return String(text||'').replaceAll('[CAT]',cat)}
function updateWording(){$('headingOut').textContent=fillWording($('heading').value);$('caption1Out').textContent=fillWording($('caption1').value);$('caption2Out').textContent=fillWording($('caption2').value);$('closingOut').textContent=fillWording($('closingHeading').value);$('caption3Out').textContent=fillWording($('caption3').value)}
$('category').onchange=()=>{const v=$('category').value;$('heading').value=v;const c=themes[v];$('color1').value=c[0];$('color2').value=c[1];setTheme();updateWording()};
['catName','heading','caption1','caption2','closingHeading','caption3'].forEach(id=>$(id).oninput=updateWording);['color1','color2'].forEach(id=>$(id).oninput=setTheme);
function objectUrl(file){const u=URL.createObjectURL(file);urls.push(u);return u}
$('catMedia').onchange=()=>{const f=$('catMedia').files[0];if(!f)return;const img=$('catImg'),vid=$('catVideo');if(f.type.startsWith('video/')){vid.src=objectUrl(f);vid.style.display='block';img.style.display='none'}else{img.src=objectUrl(f);img.style.display='block';vid.style.display='none'}applyCat()};
function applyCat(){const scale=+$('catSize').value/100,y=+$('catY').value;[$('catImg'),$('catVideo')].forEach(el=>el.style.transform=`translateY(${y}px) scale(${scale})`)}$('catSize').oninput=applyCat;$('catY').oninput=applyCat;
function prop(input,out,size){const f=$(input).files[0];if(f)$(out).src=objectUrl(f);$(out).style.width=`${105*(+$(size).value/100)}px`;$(out).style.height=`${105*(+$(size).value/100)}px`;$(out).style.display=$('useProps').checked&&$(out).src?'block':'none'}
['prop1','prop1Size'].forEach(id=>$(id).oninput=()=>prop('prop1','prop1Out','prop1Size'));['prop2','prop2Size'].forEach(id=>$(id).oninput=()=>prop('prop2','prop2Out','prop2Size'));$('useProps').onchange=()=>{prop('prop1','prop1Out','prop1Size');prop('prop2','prop2Out','prop2Size')};
$('featureMedia').onchange=()=>{const f=$('featureMedia').files[0],box=$('featureBox');if(!f)return;box.innerHTML='';if(f.type==='application/pdf'){const o=document.createElement('object');o.data=objectUrl(f);o.type='application/pdf';box.appendChild(o)}else{const i=document.createElement('img');i.src=objectUrl(f);box.appendChild(i)}};
$('musicFile').onchange=()=>{const f=$('musicFile').files[0];if(f){$('music').src=objectUrl(f);$('music').load()}};
document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>show(+b.dataset.screen));function stop(){timers.forEach(clearTimeout);timers=[];$('music').pause();$('catVideo').pause()}
function preview(){stop();updateWording();show(0);if($('music').src){$('music').currentTime=0;$('music').play().catch(()=>{})}if($('catVideo').src){$('catVideo').currentTime=0;$('catVideo').play().catch(()=>{})}timers.push(setTimeout(()=>show(1),8000),setTimeout(()=>show(2),16000),setTimeout(()=>{$('music').pause();$('catVideo').pause()},24000))}
$('preview').onclick=preview;$('stop').onclick=stop;
async function record(){if(!window.MediaRecorder){alert('This browser does not support reel recording.');return}stop();show(0);const stream=$('reel').captureStream?.(30);if(!stream){alert('Recording is not supported by this browser. Preview still works.');return}const rec=new MediaRecorder(stream,{mimeType:'video/webm'}),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));a.download='TCC-Reel.webm';a.click()};rec.start();preview();setTimeout(()=>rec.stop(),24200)}$('record').onclick=record;setTheme();updateWording();show(0);